name: Test env variable parse

on:
  push:
  pull_request:
defaults:
  run:
    shell: bash

concurrency:
  group: 'ci'
  cancel-in-progress: true

jobs:
  parse_for_flags:
    name: Check for flags in release message
    runs-on: ubuntu-latest

    steps:
      - name: Print the release author
        shell: bash
        run: |
          echo "Hello World!"
